SET SERVEROUTPUT ON;

-- Create AuditLog Table

CREATE TABLE AuditLog(

    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(20),
    LogDate DATE

);

-- Scenario 1 : Update Last Modified Date

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified

BEFORE UPDATE

ON Customers

FOR EACH ROW

BEGIN

    :NEW.LastModified := SYSDATE;

END;
/

UPDATE Customers
SET Balance = Balance + 1000
WHERE CustomerID = 1;

SELECT CustomerID,
       Name,
       LastModified
FROM Customers
WHERE CustomerID = 1;

-- Scenario 2 : Maintain Audit Log

CREATE OR REPLACE TRIGGER LogTransaction

AFTER INSERT

ON Transactions

FOR EACH ROW

BEGIN

    INSERT INTO AuditLog(

        TransactionID,
        AccountID,
        Amount,
        TransactionType,
        LogDate

    )

    VALUES(

        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE

    );

END;
/

INSERT INTO Transactions(

    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType

)

VALUES(

    101,
    1,
    SYSDATE,
    500,
    'Deposit'

);

SELECT * FROM AuditLog;

-- Scenario 3 : Check Transaction Rules

CREATE OR REPLACE TRIGGER CheckTransactionRules

BEFORE INSERT

ON Transactions

FOR EACH ROW

DECLARE

    v_balance NUMBER;

BEGIN

    SELECT Balance

    INTO v_balance

    FROM Accounts

    WHERE AccountID = :NEW.AccountID;

    IF :NEW.TransactionType = 'Withdrawal'
       AND :NEW.Amount > v_balance THEN

        RAISE_APPLICATION_ERROR(
            -20001,
            'Insufficient Balance'
        );

    END IF;

    IF :NEW.TransactionType = 'Deposit'
       AND :NEW.Amount <= 0 THEN

        RAISE_APPLICATION_ERROR(
            -20002,
            'Deposit Amount Must Be Positive'
        );

    END IF;

END;
/

-- Test Withdrawal

INSERT INTO Transactions(

    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType

)

VALUES(

    102,
    1,
    SYSDATE,
    200,
    'Withdrawal'

);

-- Test Deposit

INSERT INTO Transactions(

    TransactionID,
    AccountID,
    TransactionDate,
    Amount,
    TransactionType

)

VALUES(

    103,
    1,
    SYSDATE,
    1000,
    'Deposit'

);